### PR TITLE
fix: avoid multiple version conflict in node_modules

### PR DESCRIPTION
**Pull request by bluelovers**
http://npm.github.io/how-npm-works-docs/npm3/how-npm3-works.html

### CODE REVIEW

**Comment by achingbrain** [comment]
Could you please add some context around the problem you are trying to solve?

**Comment by bluelovers** [comment]
u can just need type `yarn link --pattern *ipfs*`

when u use in other project, will see multiple version of same package

this node_modules problem, and should try avoid bound version in dependencies by change package.json

```
├─ ipfs-repo@1.0.1 <=========
├─ ipfs-unixfs-exporter@1.0.3
├─ ipfs-unixfs-importer@0.44.1 <=========
│  └─ ipfs-unixfs@0.3.0 <=========
├─ ipfs-unixfs@1.0.1
├─ ipfs-utils@1.2.1
├─ ipfs@0.42.0
│  └─ ipfs-unixfs-importer@1.0.3 <=========
├─ ipfsd-ctl@3.0.0
│  └─ ipfs-utils@0.7.2
├─ ipld-in-memory@3.0.2
│  └─ ipfs-repo@0.30.1 <=========
├─ libp2p-delegated-content-routing@0.4.3
│  ├─ ipfs-http-client@42.0.0 <=========
│  └─ ipfs-utils@0.7.2 <=========
├─ libp2p-delegated-peer-routing@0.4.1
│  ├─ ipfs-http-client@42.0.0 <=========
│  └─ ipfs-utils@0.7.2 <=========
```

**Comment by achingbrain** [comment]
I create a new project and ran `yarn add ipfs` then listed the deps:

```console
$ yarn list --pattern *ipfs*
yarn list v1.22.4
warning package.json: No license field
warning No license field
├─ ipfs-bitswap@0.27.1
├─ ipfs-block-service@0.16.0
├─ ipfs-block@0.8.1
├─ ipfs-core-utils@0.0.1
├─ ipfs-http-client@42.0.0
│  └─ ipfs-utils@0.7.2
├─ ipfs-http-response@0.5.0
├─ ipfs-repo-migrations@0.1.1
├─ ipfs-repo@1.0.1
├─ ipfs-unixfs-exporter@1.0.3
├─ ipfs-unixfs-importer@1.0.3
├─ ipfs-unixfs@1.0.1
├─ ipfs-utils@1.2.1
├─ ipfs@0.42.0
│  └─ ipfs-http-client@43.0.0
└─ is-ipfs@0.6.3
✨  Done in 0.59s.
```

I don't see duplicate modules the same way you do (aside from `ipfs-http-client` which will be fixed by https://github.com/libp2p/js-libp2p-delegated-content-routing/pull/30 and https://github.com/libp2p/js-libp2p-delegated-peer-routing/pull/23).

Do you have other dependencies in your package.json that are causing this?

**Comment by bluelovers** [comment]
u can't always ask developer update package dep 
when they didn't change any code in project 
with that project just is a sub util lib

that's why should avoid it from package.json

**Comment by achingbrain** [comment]
Is the problem here that you are loading the wrong version of a module?  Or is it that your node_modules folder is large?

**Comment by bluelovers** [comment]
that will be hidden issue, because u can't know one of package is load wrong version

when ur new version not a semver patch

also if u try force update deps 

```json
"resolutions": {
    "ipfs-unixfs-importer": ">= 0.44.1"
  },
```

u can see just update one `ipfs-unixfs-importer` will be  avoid many package is duplicate

image

but u can't do force it, when **user** install ur package ( yarn / npm both can't fully force it when it is sub of sub package , deep... )
so better way is change package pls

if u don't like use `peerDependencies`, then pls use `>=` when ur version number always not a patch

**Comment by bluelovers** [comment]
for now it is small, if not try avoid it, one day u will see some thing like this

image

**Comment by bluelovers** [comment]
image

also if can try use something keep deps is new before u publish new version

for me, im use `yarn-tool ncu -u` for update deps, after u can use `yarn-tool install` update install

```json
  "name": "ws-ipfs",
  "version": "1.0.0",
  "private": true,
  "workspaces": [
    "packages/@lazy-ipfs/*",
    "packages/*"
  ],
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "prepublish:lockfile": "npx sync-lockfile .",
    "lerna:publish": "npx lerna publish",
    "lerna:publish:yes": "npx lerna publish --yes --cd-version patch",
    "ncu": "npx yarn-tool ncu -u && npx yarn-tool ws exec yarn-tool ncu -- -u",
    "sort-package-json": "npx yarn-tool sort"
  },
```

**Comment by achingbrain** [comment]
I really don't think this is a good idea.

A module declares a dependency on a version of another module because it is coded to the API of that version of the module.

If you then configure your project to override transitive dependency versions, there's no guarantee that loaded modules will have the expected API (known as JAR or DLL hell in other languages), leading to runtime bugs that are frequent, subtle and hard to diagnose.

**Comment by bluelovers** [comment]
when ur api is same, ur result is same, i don't think any reason, it should have multiple version exists

**Pull request closed without merging**
