### PR TITLE
Make consistent with go

### PR DESCRIPTION
**Pull request by achingbrain**
Go:

```sh
$ touch emptyfile
$ ipfs add emptyfile 
added QmbFMke1KXqnYyBBWxB74N4c5SBnJMVAiMNRcGu6x1AwQH emptyfile
$ ipfs object data QmbFMke1KXqnYyBBWxB74N4c5SBnJMVAiMNRcGu6x1AwQH | xxd
00000000: 0802 1800 
```

Without this PR:

```sh
$ jsipfs add emptyfile 
added QmfJMCvenrj4SKKRc48DYPxwVdS44qCUCqqtbqhJuSTWXP emptyfile
$ jsipfs object data QmfJMCvenrj4SKKRc48DYPxwVdS44qCUCqqtbqhJuSTWXP | xxd
00000000: 0802 1200                                ....
```

With this PR:

```sh
$ jsipfs add emptyfile 
added QmbFMke1KXqnYyBBWxB74N4c5SBnJMVAiMNRcGu6x1AwQH emptyfile
$ jsipfs object data QmbFMke1KXqnYyBBWxB74N4c5SBnJMVAiMNRcGu6x1AwQH | xxd
00000000: 0802 1800   
```

### CODE REVIEW

**Comment by achingbrain** [comment]
ipfs/js-ipfs-unixfs-engine#213 should be merged along with this PR.

**Comment by whyrusleeping** [comment]
yay... bug for bug compatibility

**Comment by achingbrain** [comment]
@diasdavid @alanshaw Any objections to merging this?

**Comment by diasdavid** [comment]
@achingbrain are there interop tests so that this doesn't bite us again?

**Comment by achingbrain** [comment]
@diasdavid I'm adding a whole bunch to the [ipfs/interop](https://github.com/ipfs/interop) repo.

**Comment by achingbrain** [comment]
These `SIGSEGV`s on the Jenkins Mac build slaves are getting ridiculous.

**Pull request merged**
