### PR TITLE
perf: exporter concurrent blockstore get

### PR DESCRIPTION
**Pull request by alanshaw**
Here's a super quick hack I did to prove the usefulness of https://github.com/ipfs/js-ipfs-unixfs/issues/236

In this PR we just concurrently fetch ALL the blocks from the blockstore if the requested byte range is the entirety of the file.

This is likely _not_ what you want to merge, but I just wanted to see something _similar_ working in practice.

In the 1st video, bitswap is having to send a message with a single block each time. We get **~40** blocks in **~30s**:

https://user-images.githubusercontent.com/152863/180323058-4ef9de24-b9d5-40dc-80fd-c75ce0da22be.mov

In the 2nd video there's a delay before receiving blocks but then we get **172** in rapid succession after **~20s**. I think the delay before receiving blocks in the second video is the server side fetching the blocks from it's blockstore (clearly not very perfromantly!):

https://user-images.githubusercontent.com/152863/180323076-f16e244b-05bc-4f11-90c2-ce7e334f4610.mov

### CODE REVIEW

**Comment by alanshaw** [comment]
P.S. I was not able to npm install in this repo after a fresh clone or run any tests...

Screenshot 2022-07-21 at 23 11 57

**Comment by lidel** [comment]
*sad Firefox noises* :crying_cat_face: 

>

**Comment by alanshaw** [comment]
I have a slightly better version of this in the fork here: https://github.com/web3-storage/fast-unixfs-exporter

Notable changes:

1. [Adds `blockReadConcurrency` option (defaults to `Infinity`)](https://github.com/web3-storage/fast-unixfs-exporter/blob/2509e5afbba19c08bcbe46e256b494e839e8e9e5/src/types.ts#L11)
2. [Wraps `blockstore.get` with `p-queue` when concurrency is less than `Infinity`](https://github.com/web3-storage/fast-unixfs-exporter/blob/2509e5afbba19c08bcbe46e256b494e839e8e9e5/src/resolvers/index.js#L44-L59)
3. [Requests all blocks for a given node from the blockstore _in parallel_, yielding blocks in the expected order as they arrive.](https://github.com/web3-storage/fast-unixfs-exporter/blob/2509e5afbba19c08bcbe46e256b494e839e8e9e5/src/resolvers/unixfs-v1/content/file.js#L135-L146)

**Comment by achingbrain** [comment]
> In the 2nd video there's a delay before receiving blocks

If the code behind the video is the code in this PR, the delay might be due to the use of [Promise.all here](https://github.com/ipfs/js-ipfs-unixfs/pull/237/files#diff-33fc6066857b57da00020e3cc0750640bc2888024463026ed9b841e17fd960f4R135) - it'll wait to load all 174 blocks before processing any of them - looks like you fixed that up in your fork though 👍 

I've tidied up the idea here in https://github.com/ipfs/js-ipfs-unixfs/pull/249 - it doesn't have a concurrency parameter right now - trivial to add but it's also limited by the number of `DAGLink`s a given `DAGNode` can have so maybe it's not necessary?

----

Something I wanted to explore with this sort of optimisation is to switch it around to use [getMany](https://github.com/ipfs/js-ipfs-interfaces/blob/master/packages/interface-store/src/index.ts#L95-L109) (though I think the return type needs to change to `AsyncIterable<Pair<Key, Value>>` first) - that would simplify the code here and shift the concurrency control to the blockstore, so for example if your blockstore is talking to a rate-limited API you might want to limit overall concurrency there, or not at all if it's in-memory.

**Comment by achingbrain** [comment]
Closing in favour of #249 - thanks for opening this!

**Pull request closed without merging**
