### PR TITLE
fix: switch to protobuf.js

### PR DESCRIPTION
**Pull request by dignifiedquire**
no more eval

### CODE REVIEW

**Comment by dignifiedquire** [comment]
we still want to commit it as otherwise installs from github will be broken

**Comment by diasdavid** [comment]
Fair, then the other 2 PR also need it commited

**Comment by dignifiedquire** [comment]
but I realised we should not auto build on releae, this file should not change most of the time, only when manipulating the proto file, so I will remove that

**Comment by dignifiedquire** [comment]
@diasdavid pushed fixes to all three PRs

**Comment by diasdavid** [comment]
@dignifiedquire did you see this:

image

Shouldn't coverage be ignoring the protobuf file?

**Comment by diasdavid** [comment]
Same issue in the other 2 PR https://github.com/ipld/js-ipld-dag-pb/issues/40

**Comment by dignifiedquire** [comment]
coverage fix coming

**Pull request closed without merging**
